/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ESPMESHMESH_APISOCKETSEND_PB_H_INCLUDED
#define PB_ESPMESHMESH_APISOCKETSEND_PB_H_INCLUDED
#include <pb.h>
#include "meshaddress.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(1024) espmeshmesh_ApiSocketSend_data_t;
typedef struct _espmeshmesh_ApiSocketSend {
    bool has_address;
    espmeshmesh_MeshAddress address;
    espmeshmesh_ApiSocketSend_data_t data;
} espmeshmesh_ApiSocketSend;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define espmeshmesh_ApiSocketSend_init_default   {false, espmeshmesh_MeshAddress_init_default, {0, {0}}}
#define espmeshmesh_ApiSocketSend_init_zero      {false, espmeshmesh_MeshAddress_init_zero, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define espmeshmesh_ApiSocketSend_address_tag    1
#define espmeshmesh_ApiSocketSend_data_tag       2

/* Struct field encoding specification for nanopb */
#define espmeshmesh_ApiSocketSend_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  address,           1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2)
#define espmeshmesh_ApiSocketSend_CALLBACK NULL
#define espmeshmesh_ApiSocketSend_DEFAULT NULL
#define espmeshmesh_ApiSocketSend_address_MSGTYPE espmeshmesh_MeshAddress

extern const pb_msgdesc_t espmeshmesh_ApiSocketSend_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define espmeshmesh_ApiSocketSend_fields &espmeshmesh_ApiSocketSend_msg

/* Maximum encoded size of messages (where known) */
#define ESPMESHMESH_APISOCKETSEND_PB_H_MAX_SIZE  espmeshmesh_ApiSocketSend_size
#define espmeshmesh_ApiSocketSend_size           1140

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
