/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ESPMESHMESH_COMMANDS_PB_H_INCLUDED
#define PB_ESPMESHMESH_COMMANDS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _espmeshmesh_Commands {
    espmeshmesh_Commands_CMD_NODE_PRESENTATION_REQ = 0,
    espmeshmesh_Commands_CMD_NODE_PRESENTATION_REP = 1
} espmeshmesh_Commands;

/* Struct definitions */
typedef struct _espmeshmesh_Command {
    bool has_command_id;
    espmeshmesh_Commands command_id;
} espmeshmesh_Command;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _espmeshmesh_Commands_MIN espmeshmesh_Commands_CMD_NODE_PRESENTATION_REQ
#define _espmeshmesh_Commands_MAX espmeshmesh_Commands_CMD_NODE_PRESENTATION_REP
#define _espmeshmesh_Commands_ARRAYSIZE ((espmeshmesh_Commands)(espmeshmesh_Commands_CMD_NODE_PRESENTATION_REP+1))

#define espmeshmesh_Command_command_id_ENUMTYPE espmeshmesh_Commands


/* Initializer values for message structs */
#define espmeshmesh_Command_init_default         {false, _espmeshmesh_Commands_MIN}
#define espmeshmesh_Command_init_zero            {false, _espmeshmesh_Commands_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define espmeshmesh_Command_command_id_tag       1

/* Struct field encoding specification for nanopb */
#define espmeshmesh_Command_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    command_id,        1)
#define espmeshmesh_Command_CALLBACK NULL
#define espmeshmesh_Command_DEFAULT NULL

extern const pb_msgdesc_t espmeshmesh_Command_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define espmeshmesh_Command_fields &espmeshmesh_Command_msg

/* Maximum encoded size of messages (where known) */
#define ESPMESHMESH_COMMANDS_PB_H_MAX_SIZE       espmeshmesh_Command_size
#define espmeshmesh_Command_size                 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
