/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ESPMESHMESH_MESHADDRESS_PB_H_INCLUDED
#define PB_ESPMESHMESH_MESHADDRESS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _espmeshmesh_ProtocolType {
    espmeshmesh_ProtocolType_SRC_NONE = 0,
    espmeshmesh_ProtocolType_SRC_BROADCAST = 1,
    espmeshmesh_ProtocolType_SRC_UNICAST = 2,
    espmeshmesh_ProtocolType_SRC_PREROUTED = 3,
    espmeshmesh_ProtocolType_SRC_MULTIPATH = 4,
    espmeshmesh_ProtocolType_SRC_POLITEBRD = 5,
    espmeshmesh_ProtocolType_SRC_BROADCAST2 = 6,
    espmeshmesh_ProtocolType_SRC_CONNPATH = 7,
    espmeshmesh_ProtocolType_SRC_STARPATH = 8,
    espmeshmesh_ProtocolType_SRC_FILTER = 254,
    espmeshmesh_ProtocolType_SRC_SERIAL = 255
} espmeshmesh_ProtocolType;

/* Struct definitions */
typedef struct _espmeshmesh_MeshAddress {
    uint32_t address;
    uint32_t port;
    pb_size_t repeaters_count;
    uint32_t repeaters[16];
    espmeshmesh_ProtocolType protocol;
} espmeshmesh_MeshAddress;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _espmeshmesh_ProtocolType_MIN espmeshmesh_ProtocolType_SRC_NONE
#define _espmeshmesh_ProtocolType_MAX espmeshmesh_ProtocolType_SRC_SERIAL
#define _espmeshmesh_ProtocolType_ARRAYSIZE ((espmeshmesh_ProtocolType)(espmeshmesh_ProtocolType_SRC_SERIAL+1))

#define espmeshmesh_MeshAddress_protocol_ENUMTYPE espmeshmesh_ProtocolType


/* Initializer values for message structs */
#define espmeshmesh_MeshAddress_init_default     {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, _espmeshmesh_ProtocolType_MIN}
#define espmeshmesh_MeshAddress_init_zero        {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, _espmeshmesh_ProtocolType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define espmeshmesh_MeshAddress_address_tag      1
#define espmeshmesh_MeshAddress_port_tag         2
#define espmeshmesh_MeshAddress_repeaters_tag    3
#define espmeshmesh_MeshAddress_protocol_tag     4

/* Struct field encoding specification for nanopb */
#define espmeshmesh_MeshAddress_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   address,           1) \
X(a, STATIC,   SINGULAR, UINT32,   port,              2) \
X(a, STATIC,   REPEATED, UINT32,   repeaters,         3) \
X(a, STATIC,   SINGULAR, UENUM,    protocol,          4)
#define espmeshmesh_MeshAddress_CALLBACK NULL
#define espmeshmesh_MeshAddress_DEFAULT NULL

extern const pb_msgdesc_t espmeshmesh_MeshAddress_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define espmeshmesh_MeshAddress_fields &espmeshmesh_MeshAddress_msg

/* Maximum encoded size of messages (where known) */
#define ESPMESHMESH_MESHADDRESS_PB_H_MAX_SIZE    espmeshmesh_MeshAddress_size
#define espmeshmesh_MeshAddress_size             111

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
