/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ESPMESHMESH_NODEPRESENTATION_PB_H_INCLUDED
#define PB_ESPMESHMESH_NODEPRESENTATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _espmeshmesh_NodePresentation {
    char hostname[49];
    char firmware_version[49];
    char compile_time[49];
} espmeshmesh_NodePresentation;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define espmeshmesh_NodePresentation_init_default {"", "", ""}
#define espmeshmesh_NodePresentation_init_zero   {"", "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define espmeshmesh_NodePresentation_hostname_tag 1
#define espmeshmesh_NodePresentation_firmware_version_tag 2
#define espmeshmesh_NodePresentation_compile_time_tag 3

/* Struct field encoding specification for nanopb */
#define espmeshmesh_NodePresentation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   hostname,          1) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   2) \
X(a, STATIC,   SINGULAR, STRING,   compile_time,      3)
#define espmeshmesh_NodePresentation_CALLBACK NULL
#define espmeshmesh_NodePresentation_DEFAULT NULL

extern const pb_msgdesc_t espmeshmesh_NodePresentation_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define espmeshmesh_NodePresentation_fields &espmeshmesh_NodePresentation_msg

/* Maximum encoded size of messages (where known) */
#define ESPMESHMESH_NODEPRESENTATION_PB_H_MAX_SIZE espmeshmesh_NodePresentation_size
#define espmeshmesh_NodePresentation_size        150

/* Message IDs (where set with "msgid" option) */
#define PB_MSG_67 espmeshmesh_NodePresentation

#define NODEPRESENTATION_MESSAGES \
	PB_MSG(67,150,espmeshmesh_NodePresentation) \

#define espmeshmesh_NodePresentation_msgid 67

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
