/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ESPMESHMESH_NODEPRESENTATIONRX_PB_H_INCLUDED
#define PB_ESPMESHMESH_NODEPRESENTATIONRX_PB_H_INCLUDED
#include <pb.h>
#include "nodepresentation.pb.h"
#include "pathrouting.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _espmeshmesh_NodePresentationRx {
    bool has_node_presentation;
    espmeshmesh_NodePresentation node_presentation;
    bool has_path_routing;
    espmeshmesh_PathRouting path_routing;
} espmeshmesh_NodePresentationRx;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define espmeshmesh_NodePresentationRx_init_default {false, espmeshmesh_NodePresentation_init_default, false, espmeshmesh_PathRouting_init_default}
#define espmeshmesh_NodePresentationRx_init_zero {false, espmeshmesh_NodePresentation_init_zero, false, espmeshmesh_PathRouting_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define espmeshmesh_NodePresentationRx_node_presentation_tag 1
#define espmeshmesh_NodePresentationRx_path_routing_tag 2

/* Struct field encoding specification for nanopb */
#define espmeshmesh_NodePresentationRx_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  node_presentation,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  path_routing,      2)
#define espmeshmesh_NodePresentationRx_CALLBACK NULL
#define espmeshmesh_NodePresentationRx_DEFAULT NULL
#define espmeshmesh_NodePresentationRx_node_presentation_MSGTYPE espmeshmesh_NodePresentation
#define espmeshmesh_NodePresentationRx_path_routing_MSGTYPE espmeshmesh_PathRouting

extern const pb_msgdesc_t espmeshmesh_NodePresentationRx_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define espmeshmesh_NodePresentationRx_fields &espmeshmesh_NodePresentationRx_msg

/* Maximum encoded size of messages (where known) */
#define ESPMESHMESH_NODEPRESENTATIONRX_PB_H_MAX_SIZE espmeshmesh_NodePresentationRx_size
#define espmeshmesh_NodePresentationRx_size      448

/* Message IDs (where set with "msgid" option) */
#define PB_MSG_69 espmeshmesh_NodePresentationRx

#define NODEPRESENTATIONRX_MESSAGES \
	PB_MSG(69,448,espmeshmesh_NodePresentationRx) \

#define espmeshmesh_NodePresentationRx_msgid 69

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
