/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ESPMESHMESH_NOTIFICATIONBEACON_PB_H_INCLUDED
#define PB_ESPMESHMESH_NOTIFICATIONBEACON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _espmeshmesh_NotificationBeacon {
    uint32_t target_address;
    pb_size_t repeaters_count;
    uint32_t repeaters[16];
    uint32_t total_cost;
} espmeshmesh_NotificationBeacon;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define espmeshmesh_NotificationBeacon_init_default {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define espmeshmesh_NotificationBeacon_init_zero {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define espmeshmesh_NotificationBeacon_target_address_tag 1
#define espmeshmesh_NotificationBeacon_repeaters_tag 2
#define espmeshmesh_NotificationBeacon_total_cost_tag 3

/* Struct field encoding specification for nanopb */
#define espmeshmesh_NotificationBeacon_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   target_address,    1) \
X(a, STATIC,   REPEATED, UINT32,   repeaters,         2) \
X(a, STATIC,   SINGULAR, UINT32,   total_cost,        3)
#define espmeshmesh_NotificationBeacon_CALLBACK NULL
#define espmeshmesh_NotificationBeacon_DEFAULT NULL

extern const pb_msgdesc_t espmeshmesh_NotificationBeacon_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define espmeshmesh_NotificationBeacon_fields &espmeshmesh_NotificationBeacon_msg

/* Maximum encoded size of messages (where known) */
#define ESPMESHMESH_NOTIFICATIONBEACON_PB_H_MAX_SIZE espmeshmesh_NotificationBeacon_size
#define espmeshmesh_NotificationBeacon_size      108

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
