/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ESPMESHMESH_PATHROUTING_PB_H_INCLUDED
#define PB_ESPMESHMESH_PATHROUTING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _espmeshmesh_PathDirection {
    espmeshmesh_PathDirection_TO_COORDINATOR = 0,
    espmeshmesh_PathDirection_TO_NODE = 1
} espmeshmesh_PathDirection;

/* Struct definitions */
typedef struct _espmeshmesh_PathRouting {
    uint32_t source_address;
    uint32_t target_address;
    pb_size_t repeaters_count;
    uint32_t repeaters[16];
    pb_size_t costs_count;
    int32_t costs[16];
    uint32_t hop_index;
    espmeshmesh_PathDirection direction;
} espmeshmesh_PathRouting;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _espmeshmesh_PathDirection_MIN espmeshmesh_PathDirection_TO_COORDINATOR
#define _espmeshmesh_PathDirection_MAX espmeshmesh_PathDirection_TO_NODE
#define _espmeshmesh_PathDirection_ARRAYSIZE ((espmeshmesh_PathDirection)(espmeshmesh_PathDirection_TO_NODE+1))

#define espmeshmesh_PathRouting_direction_ENUMTYPE espmeshmesh_PathDirection


/* Initializer values for message structs */
#define espmeshmesh_PathRouting_init_default     {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, _espmeshmesh_PathDirection_MIN}
#define espmeshmesh_PathRouting_init_zero        {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, _espmeshmesh_PathDirection_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define espmeshmesh_PathRouting_source_address_tag 1
#define espmeshmesh_PathRouting_target_address_tag 2
#define espmeshmesh_PathRouting_repeaters_tag    3
#define espmeshmesh_PathRouting_costs_tag        4
#define espmeshmesh_PathRouting_hop_index_tag    5
#define espmeshmesh_PathRouting_direction_tag    6

/* Struct field encoding specification for nanopb */
#define espmeshmesh_PathRouting_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   source_address,    1) \
X(a, STATIC,   SINGULAR, UINT32,   target_address,    2) \
X(a, STATIC,   REPEATED, UINT32,   repeaters,         3) \
X(a, STATIC,   REPEATED, INT32,    costs,             4) \
X(a, STATIC,   SINGULAR, UINT32,   hop_index,         5) \
X(a, STATIC,   SINGULAR, UENUM,    direction,         6)
#define espmeshmesh_PathRouting_CALLBACK NULL
#define espmeshmesh_PathRouting_DEFAULT NULL

extern const pb_msgdesc_t espmeshmesh_PathRouting_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define espmeshmesh_PathRouting_fields &espmeshmesh_PathRouting_msg

/* Maximum encoded size of messages (where known) */
#define ESPMESHMESH_PATHROUTING_PB_H_MAX_SIZE    espmeshmesh_PathRouting_size
#define espmeshmesh_PathRouting_size             292

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
