#pragma once
#define CMD_MAX_BUFFER_SIZE 1024

#define CMD_UART_ECHO_REQ 0x00
#define CMD_UART_ECHO_REP 0x01
#define CMD_NODE_ID_REQ 0x04
#define CMD_NODE_ID_REP 0x05
#define CMD_BIND_CLEAR_REQ 0x0A
#define CMD_BIND_CLEAR_REP 0x0B

// MeshMesh Discovery subdomain Commands
#define CMD_DISCOVERY_REQ 0x1A
#define CMD_DISCOVERY_REP 0x1B

#define CMD_LOGEVENT_REQ 0x38
#define CMD_LOGEVENT_REP 0x39

// StarPath Commands
#define CMD_NODE_PRESENTATION_REP 0x41
#define PROTO_NODE_PRESENTATION_REP 0x43
#define PROTO_NODE_PRESENTATIONRX_REP 0x45

#define CMD_BROADCAST_SEND 0x70
#define CMD_BROADCAST_RECV 0x71
#define CMD_UNICAST_SEND 0x72
#define CMD_UNICAST_RECV 0x73
#define CMD_STARPATH_SEND 0x74
#define CMD_STARPATH_RECV 0x75
#define CMD_MULTIPATH_SEND 0x76
#define CMD_MULTIPATH_RECV 0x77
#define CMD_POLITEBRD_SEND 0x78
#define CMD_POLITEBRD_RECV 0x79
#define CMD_CONNPATH_REQUEST 0x7A
#define CMD_CONNPATH_REPLY 0x7B
#define CMD_FILTERED_REQUEST 0x7C
#define CMD_FILTERED_REPLY 0x7D

#define CMD_NULL_REQ 0x7E
#define CMD_ERROR_REP 0x7F

