#pragma once

#include <functional>
#include <cstdarg>

//#define LIB_LOG_LEVEL LIB_LOG_LEVEL_DEBUG

#define LIB_LOG_LEVEL_NONE 0
#define LIB_LOG_LEVEL_ERROR 1
#define LIB_LOG_LEVEL_WARN 2
#define LIB_LOG_LEVEL_INFO 3
#define LIB_LOG_LEVEL_CONFIG 4
#define LIB_LOG_LEVEL_DEBUG 5
#define LIB_LOG_LEVEL_VERBOSE 6
#define LIB_LOG_LEVEL_VERY_VERBOSE 7

#define ESPHOME_LOG_LEVEL_NONE 0
#define ESPHOME_LOG_LEVEL_ERROR 1
#define ESPHOME_LOG_LEVEL_WARN 2
#define ESPHOME_LOG_LEVEL_INFO 3
#define ESPHOME_LOG_LEVEL_CONFIG 4
#define ESPHOME_LOG_LEVEL_DEBUG 5
#define ESPHOME_LOG_LEVEL_VERBOSE 6
#define ESPHOME_LOG_LEVEL_VERY_VERBOSE 7

/**
 * ESPHOME_LOG_LEVEL is passed from the ESPHOME  in the autogenerated platformio.ini project
 * file.  It can be used to set the log level but must be converted to numeric value.
 */
#define LIB_LOG_LEVEL ESPHOME_LOG_LEVEL

// Define log macros

#if LIB_LOG_LEVEL >= LIB_LOG_LEVEL_VERY_VERBOSE
#define LIB_LOGVV(tag, format, ...) libLog(LIB_LOG_LEVEL_VERY_VERBOSE, tag, __LINE__, format, ##__VA_ARGS__)
#else
#define LIB_LOGVV(tag, format, ...)
#endif

#if LIB_LOG_LEVEL >= LIB_LOG_LEVEL_VERBOSE
#define LIB_LOGV(tag, format, ...) libLog(LIB_LOG_LEVEL_VERBOSE, tag, __LINE__, format, ##__VA_ARGS__)
#else
#define LIB_LOGV(tag, format, ...)
#endif

#if LIB_LOG_LEVEL >= LIB_LOG_LEVEL_DEBUG
#define LIB_LOGD(tag, format, ...) libLog(LIB_LOG_LEVEL_DEBUG, tag, __LINE__, format, ##__VA_ARGS__)
#else
#define LIB_LOGD(tag, format, ...)
#endif

#if LIB_LOG_LEVEL >= LIB_LOG_LEVEL_INFO
#define LIB_LOGI(tag, format, ...) libLog(LIB_LOG_LEVEL_INFO, tag, __LINE__, format, ##__VA_ARGS__)
#else
#define LIB_LOGI(tag, format, ...)
#endif

#if LIB_LOG_LEVEL >= LIB_LOG_LEVEL_CONFIG
#define LIB_LOGCONFIG(tag, format, ...) libLog(LIB_LOG_LEVEL_CONFIG, tag, __LINE__, format, ##__VA_ARGS__)
#else
#define LIB_LOGCONFIG(tag, format, ...)
#endif

#if LIB_LOG_LEVEL >= LIB_LOG_LEVEL_WARN
#define LIB_LOGW(tag, format, ...) libLog(LIB_LOG_LEVEL_WARN, tag, __LINE__, format, ##__VA_ARGS__)
#else
#define LIB_LOGW(tag, format, ...)
#endif

#if LIB_LOG_LEVEL >= LIB_LOG_LEVEL_ERROR
#define LIB_LOGE(tag, format, ...) libLog(LIB_LOG_LEVEL_ERROR, tag, __LINE__, format, ##__VA_ARGS__)
#else
#define LIB_LOGE(tag, format, ...)
#endif

namespace espmeshmesh {
    typedef std::function<void(int level, const char *tag, int line, const char *format, va_list args)> LogCbFn;
    void setLibLogCb(LogCbFn cb);
    void libLog(int level, const char *tag, int line, const char *format, ...);
}
